- README.md
The README's link to `it-first` had an extra character, which caused the link to break.
> Fix README link to it-first

- README.md
The link to `it-to-browser-readablestream` pointed to `it-reduce`
> docs: fix the link to `it-to-browser-readablestream`

- packages/it-glob/index.js
Replace use of `fs.readdir` with `fs.opendir` as it is much faster
and consumes less memory.
When iterating over a flat directory of `1086421` files with a simple `**/*` pattern
and just counting the number of matches yielded using `it-length`:
Before:
```
counted 1086421
max heap 11.2 MB
real    2m34.757s
user    0m31.694s
sys     0m59.608s
```
After:
```
counted 1086421
max heap 8.17 MB
real    0m6.161s
user    0m4.929s
sys     0m1.583s
```
> fix: use opendir

- packages/it-glob/README.md
- packages/it-glob/index.js
- packages/it-glob/test.js
Ignores can be specified as part of the glob pattern so the extra `ignore` option is redundant.
BREAKING CHANGE: the ignore option has been removed, specify them in the glob pattern instead
> fix: remove ignore option from it-glob

- .github/workflows/test.yml
- .travis.yml
- packages/it-parallel/README.md
- packages/it-parallel/index.js
- packages/it-parallel/package.json
- packages/it-parallel/test.js
Adds an option to return ordered or unordered results, also increases default concurrency because the previous default was 1 (e.g. no concurrency).
```js
for await (const foo of parallel(source, {
ordered: true, // default: false
concurrency: 5 // default: Infinity
})) {
//...
}
```
BREAKING CHANGE: results are out-of-order by default and default concurrency has increased from 1 to Inifnity
> feat: add ordered option

- packages/it-parallel-batch/index.js
Passed directly to `it-batch` which accepts `Iterable` also: https://github.com/achingbrain/it/blob/master/packages/it-batch/index.js#L8
> fix: accepts iterable also

- packages/it-to-browser-readablestream/src/index.ts
A typescript patch update has broken the types
> fix: fix it-to-browser-readablestream-types

- packages/it-filter/README.md
- packages/it-filter/package.json
- packages/it-filter/src/index.ts
- packages/it-filter/test/index.spec.ts
Applies the same changes from #55 to it-filter
BREAKING CHANGE: if you pass a synchronous iterator and a synchronous filter function it will return a synchronous generator in response
> fix!: return iterators from synchronous sources

- packages/it-all/src/index.ts
- packages/it-batch/src/index.ts
- packages/it-batched-bytes/src/index.ts
- packages/it-drain/src/index.ts
- packages/it-first/src/index.ts
- packages/it-flat-batch/src/index.ts
- packages/it-foreach/src/index.ts
- packages/it-last/src/index.ts
- packages/it-length/src/index.ts
- packages/it-map/src/index.ts
- packages/it-map/test/index.spec.ts
- packages/it-reduce/src/index.ts
- packages/it-skip/src/index.ts
- packages/it-sort/src/index.ts
- packages/it-split/src/index.ts
- packages/it-take/src/index.ts
- packages/it-to-buffer/src/index.ts
Compatiblity fix - where the input cannot be separated between Iterable and AsyncIterable sources, update the types to return async generators.
For best performance users should pass either Iterable or AsyncIterable, not a union of both.
> fix: allow Iterable | AsyncIterable union input

- packages/it-filter/src/index.ts
- packages/it-filter/test/index.spec.ts
- packages/it-foreach/src/index.ts
- packages/it-map/package.json
- packages/it-map/src/index.ts
- packages/it-map/test/index.spec.ts
Fixes regression introduced in last major release.
> fix: yield first mapped/filtered values

- packages/it-foreach/src/index.ts
If a synchronous function is passed to `it-foreach` we don't need to `await` on the result - this artificial asynchronicity introduces unnecessary latency on hot code paths.
> fix: it-foreach should only await thenables

- packages/it-length-prefixed-stream/benchmark/stream.js
- packages/it-length-prefixed-stream/src/index.ts
- packages/it-length-prefixed-stream/test/index.spec.ts
- packages/it-protobuf-stream/src/index.ts
Adds `writeV` methods that allow us to write a number of messages or length-prefixed buffers in one go.
> feat: add `writeV` method to pb and lp streams to batch write

- packages/it-byte-stream/benchmark/stream.js
- packages/it-byte-stream/package.json
- packages/it-byte-stream/src/index.ts
- packages/it-byte-stream/src/pushable.ts
Switches from `it-pushable` to a queueless pushable and adds a transfer benchmark.
> fix: use queueless pushable for it-byte-stream outgoing data

- packages/it-length-prefixed-stream/src/index.ts
- packages/it-length-prefixed-stream/test/index.spec.ts
If a user has passed a max data length and not a max data length length, we can derive it from the max data length since we can predict how many bytes are needed to encode a given value.
> fix: derive max data length length if not passed

- packages/it-byte-stream/src/index.ts
- packages/it-length-prefixed-stream/src/index.ts
Adds a `yieldBytes` option to `it-byte-stream` that lets the user control if an unwrapped stream yields `Uint8Arrays` or `Uint8ArrayLists` before the contents of the original stream.
> fix: add option to yield objects from unwrapped byte stream

- packages/it-length-prefixed-stream/src/index.ts
To allow controlling unwrapped output pass opts to the underlying byte stream.
> fix: length-prefixed stream pass opts to byte stream

- packages/it-byte-stream/src/pushable.ts
Without this the first write to a byte/length-prefixed or protobuf stream doesn't wait for the message to be read.
> fix: await initial pushable read

- packages/it-length-prefixed-stream/package.json
- packages/it-length-prefixed-stream/src/index.ts
- packages/it-length-prefixed-stream/test/fixtures/int32BE-decode.ts
- packages/it-length-prefixed-stream/test/fixtures/int32BE-encode.ts
- packages/it-length-prefixed-stream/test/index.spec.ts
Remove usage of `it-length-prefixed` library, which was used for types and encoding logic.
- the length encoder / decoder types are now inlined (and simpler) (and backwards compatible)
- pull `decodeLength` into the body of the lp stream closure (only instantiated once, instead of on each `read`)
- manually encode the length prefix in `write` and `writeV` (this saves unnecessary function calls and allocations)
> fix: simplify lp stream read/write

- packages/it-byte-stream/package.json
- packages/it-byte-stream/src/pushable.ts
- packages/it-byte-stream/test/index.spec.ts
To prevent regresssions and ensure the contract is respected.
> fix: add read/write tests for it-byte-stream

- packages/it-filter/src/index.ts
- packages/it-filter/test/index.spec.ts
- packages/it-foreach/src/index.ts
- packages/it-foreach/test/index.spec.ts
- packages/it-map/src/index.ts
- packages/it-map/test/index.spec.ts
- packages/it-reduce/src/index.ts
- packages/it-reduce/test/index.spec.ts
Pass the current index to filter/foreach/map and reduce functions similar to Array.prototype functions.
> feat: pass index to callback functions

- packages/it-to-browser-readablestream/package.json
- packages/it-to-browser-readablestream/src/index.ts
- packages/it-to-browser-readablestream/test/index.spec.ts
Accept iterators and iterables to browser readable stream.
Fixes #123
> fix: accept iterable, convert to iterator internally

- packages/it-glob/README.md
- packages/it-glob/package.json
- packages/it-glob/src/index.browser.ts
- packages/it-glob/src/index.ts
- packages/it-glob/test/index.spec.ts
`fast-glob` is indeed fast. When running Helia's add-dir benchmark:
Before:
```
┌─────────┬───────────────────────────┬──────────┬──────────┬──────┬──────────┬──────────────────────────────────────────────────┐
│ (index) │ Implementation            │ ops/s    │ ms/op    │ runs │ p99      │ CID                                              │
├─────────┼───────────────────────────┼──────────┼──────────┼──────┼──────────┼──────────────────────────────────────────────────┤
│ 0       │ 'helia-fs - src'          │ '56.95'  │ '17.56'  │ 5    │ '53.93'  │ 'QmY7YuAvtqk9AaMR8mivfyCdSVFT4sJJwLCLYtKYfwAEKf' │
│ 1       │ 'helia-fs - dist'         │ '51.74'  │ '19.33'  │ 5    │ '81.24'  │ 'QmdHWaHWXugHHvP2y4SueC1tWUgQBrrzUHUwEMrdNEd7Cn' │
│ 2       │ 'helia-fs - ../gc/src'    │ '190.84' │ '5.24'   │ 5 …
```
> feat!: replace minimatch with fast-glob

- packages/it-glob/src/index.ts
Allow consumers to reuse the Options type without having to depend on `fast-glob` too.
> fix: re-export the Options type from fast-glob

- packages/it-byte-stream/src/pushable.ts
If no consumer is listening for the next value, and the underlying stream aborts, an unhandled promise rejection can occur.
Instead, add a `.catch` listener so the UPR doesn't occur, the rejection will be processed next time a consumer tries to read a value.
> fix: unhanded promise rejection in it-byte-stream

- packages/it-rpc/src/index.ts
- packages/it-rpc/test/index.spec.ts
Ensure `this` has the expected value when invoking a method/generator.
> fix: retain invocation context

- packages/it-byte-stream/src/errors.ts
- packages/it-byte-stream/src/index.ts
- packages/it-length-prefixed-stream/src/errors.ts
- packages/it-length-prefixed-stream/src/index.ts
Adds a .name property to errors used as rejection reasons.
> feat: add .name property to errors

- packages/it-ndjson/src/errors.ts
- packages/it-ndjson/src/index.ts
- packages/it-ndjson/src/parse.ts
- packages/it-ndjson/test/index.spec.ts
To prevent stream produces sending us streams of messages that grow too large, add an option to limit the incoming message buffer size.
> feat: add limit for incoming message sizes

- packages/it-cbor-stream/LICENSE
- packages/it-cbor-stream/LICENSE-APACHE
- packages/it-cbor-stream/LICENSE-MIT
- packages/it-cbor-stream/README.md
- packages/it-cbor-stream/package.json
- packages/it-cbor-stream/src/index.ts
- packages/it-cbor-stream/test/index.spec.ts
- packages/it-cbor-stream/tsconfig.json
- packages/it-cbor-stream/typedoc.json
Adds module for reading/writing CBOR messages in an imperative style.
> feat: add it-cbor-stream module

- packages/it-ndjson/package.json
- packages/it-ndjson/src/parse.ts
- packages/it-ndjson/test/index.spec.ts
To make parsing streams more flexible, support `Uint8ArrayList`s
> fix: support Uint8ArrayLists

- packages/it-queueless-pushable/src/index.ts
- packages/it-queueless-pushable/test/index.spec.ts
Fixes the return function to allow breaking out of a `for await..of` loop.
> fix: allow early return

- packages/it-byte-stream/package.json
- packages/it-byte-stream/src/index.ts
- packages/it-cbor-stream/package.json
- packages/it-cbor-stream/src/index.ts
- packages/it-length-prefixed-stream/package.json
- packages/it-length-prefixed-stream/src/index.ts
- packages/it-ndjson-stream/package.json
- packages/it-ndjson-stream/src/index.ts
- packages/it-protobuf-stream/package.json
- packages/it-protobuf-stream/src/index.ts
- packages/it-queueless-pushable/package.json
- packages/it-queueless-pushable/src/index.ts
Re-use the `AbortOptions` export from the `abort-error` module.
BREAKING CHANGE: the `AbortOptions` interface is no longer exported, use the one from `abort-error` instead
> fix!: remove AbortOptions exports

- packages/it-ndjson-stream/src/index.ts
- packages/it-ndjson-stream/test/index.spec.ts
- packages/it-queueless-pushable/src/index.ts
- packages/it-queueless-pushable/test/index.spec.ts
To make errors more transparent, when a pushable is ended due to
an error, re-throw that error when we try to interact with it again.
> fix: re-throw error on write to errored pushable

- packages/it-byte-stream/package.json
- packages/it-byte-stream/src/index.ts
- packages/it-byte-stream/test/index.spec.ts
- packages/it-length-prefixed-stream/src/index.ts
- packages/it-length-prefixed-stream/test/index.spec.ts
If a required number of bytes is not specified, and the underlying stream closes without yielding any bytes, return `null` instead of throwing `EOF`.
BREAKING CHANGE: if the underlying stream closes without yielding any bytes and we are not waiting for a required number of bytes, `byteStream.read` will now return `null` instead of an empty `Uint8ArrayList`
> feat!: return null from bytestream when stream closes

- packages/it-parallel/src/index.ts
- packages/it-parallel/test/index.spec.ts
If an iterable passed to `it-parallel` yields an list of values, and it throws during a delay processing those values, we need to ensure we propagate that error, otherwise calling code can stall.
> fix: handle throw during onward yield

- packages/it-merge/package.json
- packages/it-merge/src/index.ts
- packages/it-merge/test/index.spec.ts
If the consumer stops consuming from the stream, abort the add of further values to not cause hanging promises.
> fix: abort awaiting pushable add when no longer yielding values

- packages/it-rpc/src/errors.ts
- packages/it-rpc/src/index.ts
- packages/it-rpc/test/custom-types.spec.ts
- packages/it-rpc/test/index.spec.ts
If there is no onward stream to send messages to, the internal message queue grows until the process falls over.
Throw a `NotConnectedError` if there is no remote to send messages to.
> fix: require connection to invoke remote methods

- packages/it-rpc/package.json
- packages/it-rpc/src/errors.ts
- packages/it-rpc/src/index.ts
- packages/it-rpc/test/abort-signals.spec.ts
- packages/it-rpc/test/timeouts.spec.ts
Adds a timeout within which remote function calls must return to prevent slow remotes causing memory growth.
> feat: add timeout for function returns
